sudo: false

language: ruby

rvm:
  - 2.6

branches:
  only:
    - master

env:
  global:
    - MAGICK_CONFIGURE_PATH=$HOME/.config/ImageMagick
  jobs:
    - REDMINE_VER=master
    - REDMINE_VER=4.1.0
    - REDMINE_VER=4.0.6

addons:
  postgresql: "9.4"

before_install:
  # Allow imagemagick to read PDF files
  - echo $MAGICK_CONFIGURE_PATH
  - mkdir $MAGICK_CONFIGURE_PATH
  - echo '<policymap>' > $MAGICK_CONFIGURE_PATH/policy.xml
  - echo '<policy domain="coder" rights="read | write" pattern="PDF" />' >> $MAGICK_CONFIGURE_PATH/policy.xml
  - echo '</policymap>' >> $MAGICK_CONFIGURE_PATH/policy.xml
  - sudo rm /etc/ImageMagick-6/policy.xml

install: "echo skip bundle install"

before_script:
  - sudo apt-get update
  - sudo apt-get install -y ghostscript
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - export TESTSPACE=`pwd`/testspace
  - export NAME_OF_PLUGIN=redmine_omniauth_cas
  - export PATH_TO_PLUGIN=`pwd`
  - export PATH_TO_REDMINE=$TESTSPACE/redmine
  - mkdir $TESTSPACE
  - cp spec/support/* $TESTSPACE/
  - bash -x ./travis.sh
